GENRE_MAP = {
    # Gothic & Metal Gothic
    'gothic': 'Gothic',
    'gothic metal': 'Gothic',
    'gothicmetal': 'Gothic',
    'gothic rock': 'Gothic',
    'symphonic metal': 'Gothic',
    'symphonic black metal': 'Gothic',
    'symphonic death': 'Gothic',
    'gothic rock': 'Gothic',
    'german': 'Gothic',  

    # Extreme Metal & Black Metal
    'black metal': 'Extreme Metal',
    'blackmetal': 'Extreme Metal',
    'melodic black metal': 'Extreme Metal',
    'atmospheric black metal': 'Extreme Metal',
    'depressive black metal': 'Extreme Metal',
    'doom metal': 'Extreme Metal',
    'funeral doom metal': 'Extreme Metal',
    'death metal': 'Extreme Metal',
    'melodic death metal': 'Extreme Metal',
    'deathcore': 'Extreme Metal',
    'thrash metal': 'Extreme Metal',
    'doommetal': 'Extreme Metal',
    'black metal': 'Extreme Metal',
    'melodic death metal': 'Extreme Metal',
    'black metal': 'Extreme Metal',
    'black metal': 'Extreme Metal',
    'symphonic black metal': 'Extreme Metal',
    'black metal': 'Extreme Metal',
    'funeral doom metal': 'Extreme Metal',

    # Industrial & Related
    'industrial': 'Industrial',
    'industrial metal': 'Industrial',
    'industrial rock': 'Industrial',
    'ebm': 'Industrial',
    'electro-industrial': 'Industrial',
    'aggrotech': 'Industrial',
    'sid metal': 'Industrial',
    'industrial metal': 'Industrial',
    'electronic': 'Electronic',

    # Electronic & Dance
    'electronic': 'Electronic',
    'electronics': 'Electronic',
    'synthwave': 'Electronic',
    'electro house': 'Electronic',
    'breakcore': 'Electronic',
    'drum and bass': 'Electronic',
    'drum and bass': 'Electronic',
    'dnb': 'Electronic',
    'dubstep': 'Electronic',
    'house': 'Electronic',
    'hardstyle': 'Electronic',
    'darksynth': 'Electronic',
    'futurepop': 'Electronic',

    # Rock & Alternative
    'rock': 'Rock',
    'hard rock': 'Rock',
    'soft rock': 'Rock',
    'alternative': 'Alternative',
    'alternative rock': 'Alternative',
    'alternative metal': 'Alternative',
    'alternative hardcore': 'Alternative',
    'post-hardcore': 'Alternative',
    'melodic hardcore': 'Alternative',
    'emo': 'Alternative',
    'nu metal': 'Alternative',
    'post-punk': 'Punk',
    'punk': 'Punk',
    'punk rock': 'Punk',
    'siberian punk': 'Punk',
    'pop punk': 'Punk',
    'postmetal': 'Indie',
    'post-rock': 'Indie',
    'indie': 'Indie',
    'indie rock': 'Indie',
    'indie pop': 'Indie',
    'dream pop': 'Indie',
    'folk': 'Folk',
    'folk metal': 'Folk',
    'folkmetal': 'Folk',
    'folk rock': 'Folk',
    'folkrock': 'Folk',

    # Metal General
    'metal': 'Metal',
    'metalcore': 'Metal',
    'metalcoregenre': 'Metal',
    'classicmetal': 'Metal',
    'power metal': 'Metal',
    'epicmetal': 'Metal',

    # Jazz and Classical
    'jazz': 'Jazz',
    'jazz-funk': 'Jazz',
    'classical': 'Classical',
    'classical crossover': 'Classical',
    'modern': 'Classical',

    # Pop and Related
    'pop': 'Pop',
    'indie pop': 'Pop',
    'art pop': 'Pop',
    'ruspop': 'Pop',
    'new wave': 'Pop',
    'dance': 'Pop',
    'animated': 'Pop',

    # Other genres
    'country': 'Country',
    'ska': 'Ska',
    'lounge': 'Lounge',
    'experimental': 'Experimental',
    'local-indie': 'Indie',
    'rusrock': 'Russian Rock',
    'russian': 'Russian Rock',
    'rusestrada': 'Russian Estrada',
    'rusbards': 'Russian Bards',
    'soundtrack': 'Soundtrack',
    'videogame': 'Soundtrack',
    'comedy': 'Comedy',
    'films': 'Soundtrack',
    'author': 'Author',
    'chiptune': 'Electronic',
    'electro house': 'Electronic',
    'house': 'Electronic',
    'trancecore': 'Metal',
    'post-hardcore': 'Alternative',

    # Unknown and fallback
    'unknown': 'Unknown',
    '': 'Unknown',
}